# Generated by Django 3.0.8 on 2020-10-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coolapp', '0003_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='film_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coolapp.Film'),
        ),
    ]
